const express = require('express')
const router = express.Router()
const CourseController = require('../controllers/courseControllers')

router.post('/addLectureToCourseWithConditional', CourseController.AddLectureToCourse)
router.post('/registercourse', CourseController.RegisterCourse)
router.post('/deleteLectureFromCourse', CourseController.RemoveLectureFromCourse)
router.post('/searchcourse', CourseController.SearchCourses)
router.post('/UpdateCourseImage', CourseController.UpdateCourseImage)
router.get('/getListCourse', CourseController.GetListCourse)
router.get('/GetListLectureInCourse/:id', CourseController.GenerateList)
router.get('/GetLectureInCourse/:id', CourseController.GetLectureInCourse)
router.post('/addLecture', CourseController.GenerateLecture)
router.post('/nonLecture', CourseController.GenerateNonLecture)
router.post('/deleteCourse/:id', CourseController.DeleteCourse)
router.post('/updateCourse/:id', CourseController.UpdateCourse)
router.get('/getDetailCourse/:id', CourseController.GetCourse)
router.post('/createCourse', CourseController.CreateCourse)

module.exports = router